### ISSUE TITLE
Adding Documentation

### ISSUE THREAD

**Issue by raftalks** [goetas/webservices#1]
Hi, I am interested in this development as I am indeed looking for a better library to handle SOAP Requests within a PHP framework. This look to me as getting refactored with updates compared to old libraries that has been sitting in github for years.

I would like to communicate with you over email/skype/twitter if that is possible. I am interested to contribute to this project as well as help in the documentation with some examples.

**Comment by goetas** [comment]
It sounds very good!

I've developed this library to make possible some automatic conversion from xml to php objects and viceversa, and make more easy develop SOAP WS (also with IDE suggestions support),. (modern developers hate SOAP and XML, but exists a very large number of companies that use it! expecialy who use  java or net ))

Projects like goetas/xml-xsd-encoder ,  goetas/goetas-xsd-reader and goetas/wsdl-reader are just subproject.
Another interesting piece is goetas/xsd2php that creates php objects fully compatible with goetas/webservice.

If you are interested to contribute with documentation/code/debug/tests, or anything else, you are welcome!

My email is goetas@lignano.it 

What is your time zone? (for skype meeting...)

**Comment by raftalks** [comment]
Glad to hear from you.

Yeah indeed most developers would not like to develop SOAP & XML integrations, however the enterprise world is strictly based on standards and due to W3C webservice standard recommends SOAP, they all remain in that way, I  guess. 

I will send you an email with my contact details and we can further discuss on this project. My timezone is GMT +5

Thanks
