### ISSUE TITLE
Error on composer require goetas/webservices

### ISSUE THREAD

**Issue by sasha-x** [goetas/webservices#3]
Hello.
I am trying to install your lib via composer and receive error messages:

```
$ composer require goetas/webservices
Using version ~2.0 for goetas/webservices
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for goetas/webservices ~2.0 -> satisfiable by goetas/webservices[2.0.0].
    - goetas/webservices 2.0.0 requires goetas/goetas-xsd-reader ~1.0 -> no matching package found.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Installation failed, deleting ./composer.json.
```

Please, help me.

**Comment by goetas** [comment]
Can you try with 'minimum-stability':'dev' ?

**Comment by goetas** [comment]
Btw, the changes on your forked crepe looks wrong...

**Comment by sasha-x** [comment]
Error again:
$ cat composer.json
{
    "minimum-stability": "dev",
    "require": {
        "goetas/webservices": "*"
    }
}

$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
- Installing goetas/xmldom (dev-master 78a6f46)
  Cloning 78a6f468b92affbed65ea106230eb90447f4452f
- Installing goetas/goetas-xsd-reader (dev-master cffa612)
  Cloning cffa6120e930d74691c98c499539f2cba23f3507
- Installing symfony/http-foundation (2.7.x-dev ca8e158)
  Cloning ca8e158ab95c4aba3200b53dd319bc807f4ce259
- Installing symfony/event-dispatcher (2.7.x-dev ce9246f)
  Cloning ce9246f87133be616f5db06b5e162f5210f95280
- Installing guzzle/guzzle (dev-master d898326)
  Cloning d898326a716f23fdd778942ea9404aeccbe16a46
- Installing goetas/xml-xsd-encoder (dev-master 2ec1d1e)
  Cloning 2ec1d1e5df4bebcfd34a0d797cafd35205d33fd4
- Installing goetas/wsdl-reader (1.0.1-beta)
  Loading from cache
- Installing goetas/webservices (dev-master 50f3d2b)
  Cloning 50f3d2b2751942ba28ce62e6c8bac8cd020eaf27

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
guzzle/guzzle suggests installing guzzlehttp/guzzle (Guzzle 5 has moved to a new package name. The package you have installed, Guzzle 3, is deprecated.)
Package goetas/goetas-xsd-reader is abandoned, you should avoid using it. Use goetas/xsd-reader instead.
Writing lock file
Generating autoload files

**Comment by goetas** [comment]
I can not find errors in this message...

**Comment by sasha-x** [comment]
I am sorry. I was confused about message: "Package is abandoned".
Thank you.

**Comment by rafis** [comment]
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - goetas/webservices dev-soap12 requires goetas/goetas-xsd-reader ~1.0 -> no matching package found.
    - goetas/webservices 2.0.x-dev requires goetas/goetas-xsd-reader ~0.1 -> no matching package found.
    - goetas/webservices dev-master requires goetas/goetas-xsd-reader ~0.1 -> no matching package found.
    - goetas/webservices 2.0.0 requires goetas/goetas-xsd-reader ~1.0 -> no matching package found.
    - goetas/webservices 1.0.x-dev requires goetas/xml-xsd-encoder ~1.0 -> no matching package found.
    - Installation request for goetas/webservices @dev -> satisfiable by goetas/webservices[1.0.x-dev, 2.0.0, dev-master, 2.0.x-dev, dev-soap12].

**Comment by rafis** [comment]
- Installing symfony/http-foundation (2.7.x-dev 0fdfeec)                                                                                                 09:24
  Cloning 0fdfeeca4bc2ae77bfdbca2c056023d12bf08c81
- Installing symfony/event-dispatcher (2.7.x-dev 186349c)
  Cloning 186349c2966529804e38685f671e64746dde220b
- Installing guzzle/guzzle (dev-master 0645b70)
  Cloning 0645b70d953bc1c067bbc8d5bc53194706b628d9
- Installing goetas/xml-xsd-encoder (dev-master 2ec1d1e)
  Cloning 2ec1d1e5df4bebcfd34a0d797cafd35205d33fd4
- Installing goetas/wsdl-reader (1.0.1-beta)
  Downloading: connection...Failed to download goetas/wsdl-reader from dist: The "https://api.github.com/repos/goetas/wsdl-reader/zipball/5c3976a7b5c2db89e4e5
  b2d16e474d00e60d5a45" file could not be downloaded (HTTP/1.1 404 Not Found)
  Now trying to download from source
- Installing goetas/wsdl-reader (1.0.1-beta)
  Cloning 5c3976a7b5c2db89e4e5b2d16e474d00e60d5a45
  
  [RuntimeException]
  Failed to clone git@github.com:goetas/wsdl-reader.git via git, https, ssh protocols, aborting.
- git://github.com/goetas/wsdl-reader.git
  Cloning into 'D:\dev\entservices.totalegame\application\vendor\goetas/wsdl-reader'...
  fatal: remote error:
    Repository not found.
- https://github.com/goetas/wsdl-reader.git
  Cloning into 'D:\dev\entservices.totalegame\application\vendor\goetas/wsdl-reader'...
  remote: Invalid username or password.
  fatal: Authentication failed for 'https://github.com/goetas/wsdl-reader.git/'
- git@github.com:goetas/wsdl-reader.git
  Cloning into 'D:\dev\entservices.totalegame\application\vendor\goetas/wsdl-reader'...
  FATAL ERROR: Disconnected: No supported authentication methods available (server sent: publickey)
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
